sonar.projectKey=OnTime-HRMS
sonar.projectName=OnTime HRMS
sonar.projectVersion=1.0

# Direktori utama yang akan di-scan (Backend, Frontend, Mobile)
sonar.sources=backend/app,frontend/src,mobile/lib

# Pengecualian folder yang berat dan tidak perlu di-scan (seperti library pihak ketiga)
sonar.exclusions=**/vendor/**,**/node_modules/**,**/.next/**,**/build/**,**/.dart_tool/**,**/public/**,**/storage/**,**/*.test.tsx,**/*.spec.tsx,**/*Test.php

# (Opsional) Menentukan folder pengujian
sonar.tests=backend/tests
sonar.test.inclusions=**/*Test.php,**/*.test.tsx,**/*.spec.tsx
